Romicare/urls.py
from django.contrib import admin
from django.urls import path ,include
from login import views as user_view
from login import views  
from django.contrib.auth import views as auth
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path('login', views.login, name='blog_login'),
    path('logout', views.logout, name='blog_logout'),


    path('activityupload', views.activity_image_view, name='image_upload'),
    path('activity_images', views.display_activity_image, name = 'acitivity_images'),
    path('showactivity',views.showactivity, name = 'show activities'),
    path('editactivity/<int:id>', views.editactivity, name = 'edit acitivity'),  
    path('updateacitivity/<int:id>', views.updateacitivity, name = 'update acitivity'),  
    path('deleteactivity/<int:id>', views.destroyactivity, name = 'delete activity'),



    path('causeupload', views.cause_image_view, name='image_upload'),
    path('cause_images', views.display_cause_image, name = 'cause_images'),
    path('showcause',views.showcause, name = 'show causes'),
    path('editcause/<int:id>', views.editcause, name = 'edit cause'),  
    path('updatecause/<int:id>', views.updatecause, name = 'update cause'),  
    path('deletecause/<int:id>', views.destroycause, name = 'delete cause'),


    path('serviceupload', views.service_image_view, name='service_upload'),
    path('service_images', views.display_service_image, name = 'service_images'),
    path('showservice',views.showservice, name = 'show services'),
    path('editservice/<int:id>', views.editservice, name = 'edit service'),  
    path('updateservice/<int:id>', views.updateservice, name = 'update service'),  
    path('deleteservice/<int:id>', views.destroyservice, name = 'delete service'),

    path('emp', views.emp),  
    path('show',views.show, name = 'show employee'),  
    path('employeeimages', views.display_employee_image, name = 'display_employee'),
    path('edit/<int:id>', views.edit, name = 'edit employee'),  
    path('update/<int:id>', views.update, name = 'update employee'),  
    path('delete/<int:id>', views.destroy, name = 'delete employee'),


    path('blog', views.blog),  
    path('showblog',views.showblog, name = 'show blog'), 
    path('displayblog', views.displayblog, name = 'display_blogs'), 
    path('editblog/<int:id>', views.editblog, name = 'edit blog'),  
    path('updateblog/<int:id>', views.updateblog, name = 'update blog'),  
    path('deleteblog/<int:id>', views.destroyblog, name = 'delete blog'), 

    path('partner', views.partner_image_view),  
    path('showpartner',views.showpartner, name = 'show partner'), 
    path('displaypartner', views.display_partner_image, name = 'display_partners'), 
    path('editpartner/<int:id>', views.editpartner, name = 'edit partner'),  
    path('updatepartner/<int:id>', views.updatepartner, name = 'update partner'),  
    path('deletepartner/<int:id>', views.destroypartner, name = 'delete partner'),


    path('blog', views.blog),  
    path('showblog',views.showblog, name = 'show blog'), 
    path('displayblog', views.displayblog, name = 'display_blogs'), 
    path('editblog/<int:id>', views.editblog, name = 'edit blog'),  
    path('updateblog/<int:id>', views.updateblog, name = 'update blog'),  
    path('deleteblog/<int:id>', views.destroyblog, name = 'delete blog'),



    path('about', views.about),  
    path('showabout',views.showabout, name = 'show about'),
    path('', views.showuserabout ), 
    path('editabout/<int:id>', views.editabout, name = 'editabout'),  
    path('updateabout/<int:id>', views.updateabout, name = 'updateabout'),  
    path('deleteabout/<int:id>', views.destroyabout, name = 'deleteabout'), 


    path('contact', views.contact),  
    path('dashboard',views.showcontact, name = 'dashboard'),  
    path('editcontact/<int:id>', views.editcontact, name = 'edit contact'),  
    path('updatecontact/<int:id>', views.updatecontact, name = 'update contact'),  
    path('deletecontact/<int:id>', views.destroycontact, name = 'delete contact'), 



]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

login/models.py
from django.db import models
from django.contrib.auth.models import User



class Cause(models.Model):
    causetitle = models.CharField(max_length=50,default = '')
    causedescription = models.TextField(default = '')
    cause_main_img1 = models.ImageField(upload_to='images/',default = '')
    cause_main_img2 = models.ImageField(upload_to='images/',default = '')
    cause_main_img3 = models.ImageField(upload_to='images/',default = '')
    cause_main_img4 = models.ImageField(upload_to='images/',default = '')
    cause_main_img5 = models.ImageField(upload_to='images/',default = '')
    cause_main_img6 = models.ImageField(upload_to='images/',default = '')
    class Meta:  
        db_table = "cause" 


class Service(models.Model):
    servicecategory = models.CharField(max_length=50,default = '', blank=True )
    servicetitle = models.CharField(max_length=50,default = '', blank=True )
    servicedescription1 = models.TextField(default = '',blank=True )
    servicedescription2 = models.TextField(default = '',blank=True )
    servicedescription3 = models.TextField(default = '',blank=True )
    service_main_img = models.ImageField(upload_to='images/', blank=True )
  
    
    class Meta:  
        db_table = "service" 



class Employee(models.Model):    
    ename = models.CharField(max_length=100,default = '')  
    eemail = models.EmailField(default = '')  
    econtact = models.CharField(max_length=15,default = '')
    edescription = models.TextField(default = '')

    class Meta:  
        db_table = "employee" 


class Contact(models.Model):  
    commentname = models.CharField(max_length=100, default = '') 
    commentemail = models.EmailField(default = '') 
    commentsubject = models.TextField(default = '')  
    commentmessage = models.TextField(default = '') 
    class Meta:  
        db_table = "contact" 


class Respond(models.Model):  
    respondmessage = models.TextField(default = '') 
    class Meta:  
        db_table = "response" 


class Donation(models.Model):  
    dname = models.CharField(max_length=100 ,default = '') 
    damount = models.CharField(max_length=100 ,default = '') 
    dtype = models.CharField(max_length=15 ,default = '')
    dcause = models.CharField(max_length=15 ,default = '')  
           
    class Meta:  
        db_table = "donation" 


class Blog(models.Model):  
    btitle = models.CharField(max_length=100,default = '')  
    bauthor = models.CharField(max_length = 100, default='') 
    bdescription = models.TextField(default = '') 
    byoutubelink = models.TextField(default = '') 
       
    class Meta:  
        db_table = "blog" 

        

class About(models.Model):  
    projectname = models.CharField(max_length=100 ,default = '',blank=True) 
    mission = models.TextField(default = '',blank=True)
    vision = models.TextField(default = '',blank=True)
    objective1 = models.TextField(default = '',blank=True)
    objective2 = models.TextField(default = '',blank=True) 
    objective3 = models.TextField(default = '',blank=True) 
    objective4 = models.TextField(default = '',blank=True) 
    objective5 = models.TextField(default = '',blank=True)
    testimonial1 = models.CharField(max_length=100,default = '',blank=True) 
    testimonialrole1 = models.CharField(max_length=100,default = '',blank=True  ) 
    testimonialdecription1 = models.TextField(default = '',blank=True)
    testimonial2 = models.CharField(max_length=100,default = '',blank=True) 
    testimonialrole2 = models.CharField(max_length=100,default = '',blank=True) 
    testimonialdecription2 = models.TextField(default = '',blank=True)
    testimonial3 = models.CharField(max_length=100,default = '',blank=True) 
    testimonialrole3 = models.CharField(max_length=100,default = '',blank=True) 
    testimonialdecription3 = models.TextField(default = '',blank=True)
    testimonial4 = models.CharField(max_length=100,default = '',blank=True) 
    testimonialrole4 = models.CharField(max_length=100,default = '',blank=True) 
    testimonialdecription4 = models.TextField(default = '',blank=True)
    testimonial5 = models.CharField(max_length=100,default = '',blank=True) 
    testimonialrole5 = models.CharField(max_length=100,default = '',blank=True) 
    testimonialdecription5 = models.TextField(default = '',blank=True) 
    location1 = models.CharField(max_length=100,default = '',blank=True) 
    location2 = models.CharField(max_length=100,default = '',blank=True  )
    contact1 = models.CharField(max_length=100,default = '',blank=True) 
    contact2 = models.CharField(max_length=100,default = '',blank=True  )
    Amount1 = models.CharField(max_length=100,default = '',blank=True  )
    Amount2 = models.CharField(max_length=100,default = '',blank=True  )
    Amount3 = models.CharField(max_length=100,default = '',blank=True  )
    Amount4 = models.CharField(max_length=100,default = '',blank=True  )
    Amount5 = models.CharField(max_length=100,default = '',blank=True  )
    Amount6 = models.CharField(max_length=100,default = '',blank=True  )
    status1 = models.CharField(max_length=100,default = '',blank=True  )
    status2 = models.CharField(max_length=100,default = '',blank=True  )
    status3 = models.CharField(max_length=100,default = '',blank=True  )
    status4 = models.CharField(max_length=100,default = '',blank=True  )
    status5 = models.CharField(max_length=100,default = '',blank=True  )
    status6 = models.CharField(max_length=100,default = '',blank=True  )
    genderequity = models.CharField(max_length=100,default = '',blank=True  )
    skills = models.CharField(max_length=100,default = '',blank=True  )
    education = models.CharField(max_length=100,default = '',blank=True  )
    climatechange = models.CharField(max_length=100,default = '',blank=True  )
    livelihoods = models.CharField(max_length=100,default = '',blank=True  )
    sustainabledevelopment = models.CharField(max_length=100,default = '',blank=True  )




    class Meta:  
        db_table = "about" 




class Partner(models.Model):  
    partnername = models.CharField(max_length=100,default = '',blank=True)  
    partnerdescription = models.TextField(default = '',blank=True) 
    partner_main_img = models.ImageField(upload_to='images/' , default = '')   
  
    class Meta:  
        db_table = "partner" 


class Member(models.Model):  
    membername = models.CharField(max_length=100,default = '',blank=True) 
    memberemail = models.EmailField(default = '')  
    memberusername = models.ImageField(upload_to='images/' , default = '')   
  
    class Meta:  
        db_table = "member" 



class Activity(models.Model):
    activitytitle = models.CharField(max_length=50,default = '')
    activitydescription = models.TextField(default = '')
    activity_main_img1 = models.ImageField(upload_to='images/',default = '' )
    activity_main_img2 = models.ImageField(upload_to='images/',default = '') 
    activity_main_img3 = models.ImageField(upload_to='images/',default = '' ) 
    activity_main_img4 = models.ImageField(upload_to='images/', default = '') 
    activity_main_img5 = models.ImageField(upload_to='images/', default = '')  
    activity_main_img6 = models.ImageField(upload_to='images/', default = '')

    class Meta:  
        db_table = "activity" 

login/forms.py
from django import forms  
from login.models import Employee  ,About ,Contact ,Blog ,Cause  ,Service ,Activity ,Donation ,Partner ,Member 
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm



class LoginForm(forms.Form):
    username = forms.CharField(max_length=65)
    password = forms.CharField(max_length=65, widget=forms.PasswordInput)


class MemberForm(forms.ModelForm):
 
    class Meta:
        model = Member
        fields = "__all__" 


class ActivityForm(forms.ModelForm):
 
    class Meta:
        model = Activity
        fields = "__all__" 

 
class CauseForm(forms.ModelForm):
 
    class Meta:
        model = Cause
        fields = "__all__" 

 
class ServiceForm(forms.ModelForm):
 
    class Meta:
        model = Service
        fields = "__all__" 


class EmployeeForm(forms.ModelForm):  
    class Meta:  
        model = Employee  
        fields = "__all__"  

    
class BlogForm(forms.ModelForm):  
    class Meta:  
        model = Blog  
        fields = "__all__"  


class CauseForm(forms.ModelForm):  
    class Meta:  
        model = Cause  
        fields = "__all__"  


class AboutForm(forms.ModelForm):  
    class Meta:  
        model = About  
        fields = "__all__" 
        


class ContactForm(forms.ModelForm):  
    class Meta:  
        model = Contact  
        fields = "__all__" 


class DonateForm(forms.ModelForm):  
    class Meta:  
        model = Donation  
        fields = "__all__" 


class PartnerForm(forms.ModelForm):  
    class Meta:  
        model = Partner  
        fields = "__all__" 



class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()
    phone_no = forms.CharField(max_length = 20)
    first_name = forms.CharField(max_length = 20)
    last_name = forms.CharField(max_length = 20)
    class Meta:
        model = User
        fields = ['username', 'email', 'phone_no', 'password1', 'password2']

login/templates/base.html
{% load static %}
<!DOCTYPE html>  
<html lang="en">  

<head>  
    <title>ROCAF</title>
    <link href="{% static 'assets/img/log.jpg' %}" rel="icon">
  <link href="{% static 'assets/img/log.jpg' %}" rel="icon">
   
    <meta charset="UTF-8">  
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=yes">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

 <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>


</head>  
<body> 
 <!-- Navbar -->


 <div class="container">
<nav class="navbar navbar-expand-lg navbar navbar-light" style="background-color: ghostwhite; ">

  <div class="container">


    <!-- Collapsible wrapper -->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <!-- Navbar brand -->
      <a class="navbar-brand mt-2 mt-lg-0" href="#">
        <img
          src="{% static 'assets/img/log.jpg' %}"
          height="200"
          alt=""
          loading="lazy"
        />
      </a>
      <div>

      <a href="/showpartner" class="btn btn-primary outlined-pill"><strong>partners</strong></a>


      <a href="/showactivity" class="btn btn-warning outlined-pill"><strong>activities</strong></a>

      
     <a href="#" class="btn btn-danger outlined-pill"><strong>donations</strong></a>
    
    </div>
      <ul class="navbar-nav mr-auto mt-2 mt-lg-2">
      <li class="nav-item active">
        <a class="nav-link active " href="/dashboard"><strong>Dashboard</strong><span class="sr-only">(current)</span></a>
      </li>

      <li class="nav-item">
        <a class="nav-link active" href="/showservice"><strong>Services</strong></a>
      </li>

          <li class="nav-item">
        <a class="nav-link active" href="/showabout"><strong>About</strong></a>
      </li>
     
     
         <li class="nav-item">
        <a class="nav-link active" href="/showblog"><strong>Blogs</strong></a>
      </li>
     
          <li class="nav-item">
        <a class="nav-link active" href="/show"><strong>Team</strong></a>
      </li>
     
           <li class="nav-item">
        <a class="nav-link active" href="/showcause"><strong>Causes</strong></a>
      </li>
     
    </ul>
    <div>

    
    </div>


    <div>

    <form class="form-inline my-2 my-lg-0">
     
    <center><a href="/login" class="btn btn-outline-success rounded-pill"><strong>SIGNOUT</strong></a></center> 
    </form>

</div>
</div>
 
</nav>
<!-- Navbar -->
  
    <div class="content">
        {% block content %} {% endblock %}
    </div>

    </div>
    </div>

     <footer id="footer">
    <div class="card-footer bg-transparent border-green">
    <div class="container">
      <center><strong>R O M I C  C A R E  F O U N D A T I O N</strong></center>

     <center><div class="copyright">
        &copy; Copyright <strong><span>R O C A  F</span></strong>. All Rights Reserved
      </div></center>
    </div>
  </div>

</footer>
</body>  
</html>  

login/templates/base3.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>ROCAF</title>
    <link href="{% static 'assets/img/log.jpg' %}" rel="icon">
  <link href="{% static 'assets/img/log.jpg' %}" rel="icon">
   
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=100">
   
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
</head>
<body>
   

            {% block content %}{% endblock %}
   
   
  
</body>
</html>

login/templates/blog.html
{% extends 'base.html' %}

{% block content %}

<div class="card-body">

    <div class="form-group col">  
    <label class="row-sm-12 col-form-label row-lg-20"></label>  
    <div class="col-sm-12">  
    <h3><strong>B L O G S     </strong></h3> 
    <p> <strong>Add Blogs </strong></p> 
    </div>  
  </div> 


<form method="POST" class="post-form" action="/blog">  
        {% csrf_token %}  
   

   <div class="row mt-1">
    <label class="col-sm-4 col-form-label"><strong> BLOG TITLE:  </strong></label>  
     <div class="col-sm-12">  
      <div class="card"> 
      {{ form.btitle }} 
      </div> 
    </div>  
  </div> 

   <div class="row mt-1">
    <label class="col-sm-4 col-form-label"><strong> BLOG AUTHOR:  </strong></label>  

    <div class="col-sm-12">  
      <div class="card"> 
      {{ form.bauthor }} 
      </div> 
    </div>  
  </div> 
 
      <div class="row mt-1">
    <label class="col-sm-4 col-form-label"><strong> BLOG DESCRIPTION:  </strong></label>  

    <div class="col-sm-12">  
      <div class="card"> 
      {{ form.bdescription }} 
      </div> 
    </div>  
  </div> 

  
    <div class="row mt-1">
    <label class="col-sm-4 col-form-label"><strong> BLOG YOUTUBE LINK:  </strong></label>  

    <div class="col-sm-12">  
      <div class="card"> 
      {{ form.byoutubelink }} 
      </div> 
    </div>  
  </div>

    
<br/>
<br/>

    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-12">  
    <button type="submit" class="btn btn-success">Upload Blog</button>  
    </div>  
  </div>  
    </div>  
</form>  



{% endblock %}

login/templates/display_activity_images.html
{% extends 'base2.html' %}
{% block content %}


<section>


<div class="container">
	   <div class="card-title">
              
              <nav class="d-flex justify-content-end">
                <ol class="breadcrumb">
                  <li class="breadcrumb-item"><a href="/"><strong>Home</strong></a></li>
                  <li class="breadcrumb-item"><a href="#"><strong>Recent OUTREACH</strong></a></li>
                
                </ol>
              </nav>
            </div>
        </div>

  

	{% for activity in activity_images %}
	
	<div class="container">
		<div class="card-body justify-content-center">

			<div class="row">

				<div>

	<div class="container">
				
          <div class="col-xl-12"> 

          			
          		<div class="card-title">
          <div class="container">
          
         <ol class="breadcrumb">
          <br/>
          <br/>
          <br/>
         <center> <li class="breadcrumb-item"><a href="#"><h2><strong><center><strong>{{ activity.activitytitle }}</strong></center></strong></h2></a></li></center>
         
          
        </ol>
      </div>
          
       <div class="card-body	display_partner_images.html">
          <div class="container">
          			 <div class="row mt-1">
                  <div class="card-body">
          			 	<center><label class="col-sm-12 col-form-label"><strong><p>"{{ activity.activitydescription }} "</p></label></center> 
                 </div>

     
         </div>
       </div>
       </div>
					<br/>
					<div class="card">

					<div class="container">
				<div class="card-body">


				<center><img src="{{ activity.activity_main_img1.url }}" class="img-fluid" alt="Responsive Image" width="500" height="500" /></center>
			</div>
		</div>
					<br/>

					<div class="container">
				<div class="card-body">


				<center><img src="{{ activity.activity_main_img2.url }}" class="img-fluid" alt="Responsive Image" width="500" height="500" /></center>
			</div>
		</div>
						<br/>
					<div class="container">
				
			<div class="card-body">

				<center><img src="{{ activity.activity_main_img3.url }}" class="img-fluid" alt="Responsive Image" width="500" height="500" /></center>
			</div>
</div>
			<br/>

				

					<div class="container">
				
			<div class="card-body">
				<center><img src="{{ activity.activity_main_img4.url }}" class="img-fluid" alt="Responsive Image" width="500" height="500" /></center>
			</div>
				<br/>
					<div class="container">

					<div class="card-body">

				<center><img src="{{ activity.activity_main_img5.url }}" class="img-fluid" alt="Responsive Image" width="500" height="500" /></center>

					
			</div>
		</div>
					<br/>
	

					<div class="container">
				
			<div class="card-body">

				<center><img src="{{ activity.activity_main_img6.url }}" class="img-fluid" alt="Responsive Image" width="500" height="500" /></center>
			</div>

					</div>
					<br/>


	

	
			<div class="container">
				<center><button type="button" class="btn btn-danger"><strong> D O N A T E </strong></button></center>
			</div>

				<br/>
		<br/>
			
	
	</div>
		</div>


	
</div>

</div>



		</section>


	{% endfor %}


{% endblock %}

login/templates/display_cause_images.html
{% extends 'base2.html' %}
{% block content %}


<section>


<div class="container">
	   <div class="card-title">
              
              <nav class="d-flex justify-content-end">
                <ol class="breadcrumb">
                  <li class="breadcrumb-item"><a href="/"><strong>Home</strong></a></li>
                  <li class="breadcrumb-item"><a href="#"><strong>Ongoing & InComing Events</strong></a></li>
                
                </ol>
              </nav>
            </div>
        </div>
    

	{% for cause in cause_images %}
	
	<div class="container">
		<div class="card-body justify-content-center">

			<div class="row">
				
          <div class="col-xl-12">        
          			
          		
          				<div class="card-title ">
          				<h4>
             			<center><strong>{{ cause.causetitle }}</strong></h4></center>
             		</div>
          		
					<div class="card-body">
			<center><p>"{{ cause.causedescription }}"</p></center>
			</div>
		
		
				 	<div class="row">


				<img src="{{ cause.cause_main_img1.url }}" class="rounded-circle" style="width: 33%; float: center margin-between: 10px;" />

				<img src="{{ cause.cause_main_img2.url }}" class="rounded-circle" style="width: 33%; float: center margin-between: 10px;" />
		
				<img src="{{ cause.cause_main_img3.url }}" class="rounded-circle" style="width: 33%; float: center margin-between: 10px;" />
			
				<img src="{{ cause.cause_main_img4.url }}" class="rounded-circle" style="width: 33%; float: center margin-between: 10px;" />
					
				<img src="{{ cause.cause_main_img5.url }}" class="rounded-circle" style="width: 33%; float: center margin-between: 10px;" />
				
				<img src="{{ cause.cause_main_img6.url }}" class="rounded-circle" style="width: 33%; float: center margin-between: 10px;" />
		
				

				</div>
		<br/>
		
	

	
			<div class="container">
				<center><button type="button" class="btn btn-danger"><strong> D O N A T E </strong></button></center>
			</div>

				<br/>
		<br/>
			
		
	</div>

		


	
</div>

</div>



		</section>


	{% endfor %}


{% endblock %}

login/templates/editcontactus.html
{% extends 'base.html' %}

{% block content %}
<nav>
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="/contact"><stong>showcontact Comments</strong></a></li>
          <li class="breadcrumb-item"><strong>Respond</strong> </li>
               
        </ol>
      </nav>

<form method="POST" class="post-form" action="/updatecontact/{{contact.id}}">  
        {% csrf_token %}  

        <div class="container">  

             <div class="form-group col">  
    <label class="row-sm-12 col-form-label row-lg-20"></label>  
    <div class="col-sm-12">  
    <h3><strong> HOME AND EDUCATION FOUNDATION UGANDA </strong></h3> 
    <p> <strong>Response To Comments Shared  </strong></p> 
    </div>  
  </div> 
 <div class="row mt-1">
    <label class="col-sm-12 col-form-label"><strong> MESSAGE SENT BY:  </strong></label> 
    <div class="col-sm-12">  
        <div class="card">
        <input type="text" name="commentname" id="id_commentname" required maxlength="100" value="{{ contact.commentname }}" />  
    </div>  
</div>
  </div>  

<br/>

    <div class="row mt-1">
    <label class="col-sm-12 col-form-label"><strong> SENDER EMAIL ADDRESS:  </strong></label> 
    <div class="col-sm-12">  
        <div class="card">
        <input type="text" name="commentemail" id="id_commentemail" required maxlength="100" value="{{ contact.commentemail }}" />  
    </div>  
</div>
  </div>  

<br/>
    <div class="row mt-1">
    <label class="col-sm-12 col-form-label"><strong> SUBJECT:  </strong></label> 
    <div class="col-sm-12">  
        <div class="card">
        <input type="text" name="commentsubject" id="id_commentsubject" required maxlength="254" value="{{ contact.commentsubject }}" />  
    </div>  
</div>
</div>

<br/>

<div class="row mt-1">
    <label class="col-sm-12 col-form-label"><strong> COMMENT SENT:  </strong></label> 
    <div class="col-sm-12">  
        <div class="card">
        <input type="text" name="commentmessage" id="id_commentmessage" required maxlength="254" value="{{ contact.commentmessage }}" />  
    </div>  
 
  </div> 
</div>
  <br/> 
    <div class="row mt-1">
      <label for="inputPassword" class="col-sm-12 col-form-label"><strong>RESPOND TO MESSAGE</strong></label>
       <div class="col-sm-12">
        <div class="card">
        <textarea class="form-control" style="height: 100px"></textarea>
                  </div>
                </div>
            </div>
            <br/>

    <div class="form-group row">  
    <label class="col-sm-12 col-form-label"></label>  
    <div class="col-sm-12">  
         <center><a href="#" class="btn btn-success"><strong> SEND RESPONSE</strong></a></center>
      
    </div>  
  </div>  
    </div>  
</form>  

{% endblock %}